### PR TITLE
Huge Cleanup / Delete / Fix for Scrapers

### PR DESCRIPTION
**Pull request by SerpentDrago**
I went though some of the (All)  scrapers , and Deleted non working ones , fixed a few (at least i think i fixed them ) and removed a few Duplicates . 

Still much work needs to be done but its a start !

### CODE REVIEW

**Comment by SerpentDrago** [comment]
Prob should mark this as pulled , why did it not auto close ?

**Comment by SerpentDrago** [comment]
Ohh they are approved , but not merged yet

**Comment by JonnyGadd** [comment]
Awesome! I thought the duplicate scraper was already removed in the latest update?

**Comment by turtlestv** [comment]
I didn't close it I agreed during the review.

**Comment by SerpentDrago** [comment]
There is  prob more duplicates and non working ones lol , this is just a first pass . its a mess !!!

**Pull request merged**
