### PR TITLE
Make Lambda Scrapers  default

### PR DESCRIPTION
**Pull request by SerpentDrago**
Why not just make Lambda Scrapers default enabled ? this should do it right ?

### CODE REVIEW

**Comment by SerpentDrago** [comment]
Merge with Master

**Comment by SerpentDrago** [comment]
Is there a reason you won't just make Lambda scrapers enabled by default ?

**Comment by I-A-C** [comment]
I deliberately disabled Lambdascrapers in Exodus Redux because I was trying to create some separation between the video add-on and the module itself.  I wanted the user to have to make a deliberate choice to use the module.  

My bad for making it a little too obscure.  A couple of dialog boxes opting into the Lambdascraper module would probably be a neater way of achieving this.

**Comment by SerpentDrago** [comment]
Fair enough !

**Pull request closed without merging**
